### ISSUE TITLE
PECL extension install fails

### ISSUE THREAD

**Issue by robsontenorio** [php-kafka/php-kafka#60]
* PHP version: 8.0.12
 * librdkafka version: 1.6.0
 * simple-kafka-client version: - 
 * kafka version: -

**Ubuntu 21.10**

```
pecl install simple_kafka_client
```
Error: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /usr/share/php/PEAR/Config.php on line 2095

**Comment by nick-zh** [comment]
@robsontenorio thx for reporting, is there some code you can share? I would assume you are accessing an array with e.g. `$arr{0}` which is no longer supported

**EDIT:** i tried it with the setup you mentioned (used alpine though instead of ubuntu), did not have any problems, so i am assuming it is user related code. Let me know if i can help any further :v:

**Comment by robsontenorio** [comment]
No code yet. Just tried to run install command on Ubuntu 21.10

I will try provide some Dockerfile with more confident reproduced steps.

**Comment by nick-zh** [comment]
@robsontenorio i found similar problems from other projects, it seems that is caused by an outdated pear / pecl problem, see [here](https://github.com/laravel/sail/issues/173#issuecomment-879538228). This would make sense with the path you provided, since the extension does not provide any php files :v:

**Comment by robsontenorio** [comment]
That’s it. Thanks @nick-zh 

Looking forward for your YouTube videos. Don’t give up :)
